name: GNU Guile 3.0

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install  \
              guile-3.0-dev \
              gcc           \
              gettext       \
              automake      \
              autoconf      \
              texinfo       \
              pkg-config
        
      - name: Checkout repository 
        uses: actions/checkout@v2

      - name: Autoreconf
        run: autoreconf -vif

      - name: Configure
        run: ./configure

      - name: Run tests
        run: make check

