name: GNU Guile 2.2

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install  \
              guile-2.2-dev \
              make          \
              gcc           \
              udev          \
              libudev-dev   \
              gettext       \
              automake      \
              autoconf      \
              texinfo       \
              pkg-config
        
      - name: Checkout repository 
        uses: actions/checkout@v2

      - name: Autoreconf
        run: autoreconf -vif

      - name: Configure
        run: ./configure

      - name: Run tests
        run: make check

